---
- name: "ensure nginx-gen container is {{ state }}"
  docker:
    name: "nginx-gen"
    image: "{{ docker_images.nginx_gen }}"
    state: "{{ state }}"
    restart_policy: always
    volumes_from:
      - nginx
    volumes:
      - "{{ nginx_gen_data_folder }}:/etc/docker-gen/templates"
      - /var/run/docker.sock:/tmp/docker.sock
    command: -notify-sighup nginx -watch --only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf